api:
  paths:
    create_challenge: /create_challenge
    create_group: /create_group
    delete_challenge: /delete_challenge
    get_challenge_data: /get_challenge_data
    get_challenges: /get_challenges
    get_group_data: /get_group_data
    get_groups: /get_groups
    get_group_members: /get_group_members
    get_user_challenges: /get_user_challenges
    get_user_data: /get_user_data
    get_users: /get_users
    join_group: /join_group
    login: /login
    register: /register
    update_challenge: /update_challenge
mysql:
  host: 192.168.1.56
  name: treasure_hunt_db
  pw: treasurehunt5901
  user: treasure_hunt
paths:
  emails: /home/ritwik/git_hub/TreasureHunt/backend/emails/
security:
  secret_key: 1p7TqwPUIZxfV09yMzXc
smtp:
  email: thetreasurehuntteam@gmail.com
  port: 587
  pw: teamtreasurehunt5901
  server: smtp.gmail.com
