api:
  paths:
    complete_challenge: /complete_challenge
    create_challenge: /create_challenge
    create_group: /create_group
    delete_challenge: /delete_challenge
    download_pfp: /download_pfp
    get_challenge_data: /get_challenge_data
    get_challenges: /get_challenges
    get_group_data: /get_group_data
    get_groups: /get_groups
    get_group_members: /get_group_members
    get_group_row: /get_group_row
    get_group_settings: /get_group_settings
    get_user_challenges: /get_user_challenges
    join_group: /join_group
    leave_group: /leave_group
    login: /login
    register: /register
    remove_group_member: /remove_group_member
    reset_password: /reset_password
    send_email_reset_password: /send_email_reset_password
    update_challenge: /update_challenge
    update_group_settings: /update_group_settings
    upload_pfp: /upload_pfp
    verify_account: /verify_account/{email_verify_token}
firebase_storage:
  db_backups: database_backups/
  profile_pictures: profile_pictures/
mysql:
  host: 192.168.1.56
  name: treasure_hunt_db
  pw: treasurehunt5901
  root_pw: mysqlpw5901
  user: treasure_hunt
paths:
  html_bodies: /home/ritwik/git_hub/TreasureHunt/backend/html_bodies/
  emails: /home/ritwik/git_hub/TreasureHunt/backend/emails/
  firebase_config: /home/ritwik/git_hub/TreasureHunt/backend/firebase_config.json
  tmp: /home/ritwik/git_hub/TreasureHunt/backend/tmp/
security:
  secret_key: 1p7TqwPUIZxfV09yMzXc
smtp:
  email: thetreasurehuntteam@gmail.com
  port: 587
  pw: teamtreasurehunt5901
  server: smtp.gmail.com
