api:
  paths:
    accept_invitation: /api/accept_invitation
    complete_challenge: /api/complete_challenge
    create_challenge: /api/create_challenge
    create_group: /api/create_group
    create_race: /api/create_race
    decline_invitation: /api/decline_invitation
    delete_challenge: /api/delete_challenge
    download_pfp: /api/download_pfp
    get_challenge_data: /api/get_challenge_data
    get_challenges: /api/get_challenges
    get_group_data: /api/get_group_data
    get_groups: /api/get_groups
    get_group_members: /api/get_group_members
    get_group_row: /api/get_group_row
    get_group_settings: /api/get_group_settings
    get_invitations: /api/get_invitations
    get_messages: /api/get_messages
    get_user_challenges: /api/get_user_challenges
    invite_user: /api/invite_user
    join_group: /api/join_group
    leave_group: /api/leave_group
    login: /api/login
    register: /api/register
    remove_group_member: /api/remove_group_member
    reset_password: /api/reset_password
    send_email_reset_password: /api/send_email_reset_password
    send_message: /api/send_message
    update_challenge: /api/update_challenge
    update_group_settings: /api/update_group_settings
    upload_pfp: /api/upload_pfp
    verify_account: /verify_account/{email_verify_token}
firebase_storage:
  db_backups: database_backups/
  profile_pictures: profile_pictures/
mysql:
  host: 192.168.1.56
  name: treasure_hunt_db
  pw: treasurehunt5901
  root_pw: mysqlpw5901
  user: treasure_hunt
paths:
  html_bodies: /home/ritwik/git_hub/TreasureHunt/backend/html_bodies/
  emails: /home/ritwik/git_hub/TreasureHunt/backend/emails/
  firebase_config: /home/ritwik/git_hub/TreasureHunt/backend/firebase_config.json
  tmp: /home/ritwik/git_hub/TreasureHunt/backend/tmp/
security:
  secret_key: 1p7TqwPUIZxfV09yMzXc
smtp:
  email: thetreasurehuntteam@gmail.com
  port: 587
  pw: teamtreasurehunt5901
  server: smtp.gmail.com
