api:
  paths:
    login: /login
    register: /register
    create_challenge: /create_challenge
    create_group: /create_group
mysql:
  host: 192.168.1.56
  name: treasure_hunt_db
  pw: treasurehunt5901
  user: treasure_hunt
paths:
  emails: /home/ritwik/git_hub/TreasureHunt/backend/emails/
smtp:
  email: thetreasurehuntteam@gmail.com
  port: 587
  pw: teamtreasurehunt5901
  server: smtp.gmail.com
